all: spawnA hijo1 SpawnB SpawnC SpawnD hijo2 SpawnE

spawnA: spawnA.c
	gcc -o spawnA spawnA.c

SpawnB: SpawnB.c
	gcc -o SpawnB SpawnB.c

SpawnC: SpawnC.c
	gcc -o SpawnC SpawnC.c

SpawnD: SpawnD.c
	gcc -o SpawnD SpawnD.c

SpawnE: SpawnE.c
	gcc -o SpawnE SpawnE.c

hijo1: hijo1.c
	gcc -o hijo1 hijo1.c

hijo2: hijo2.c
	gcc -o hijo2 hijo2.c

clean: 
	rm spawnA hijo1 SpawnB SpawnC SpawnD hijo2 SpawnE


